<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;

require_once path .'/vendor/neoan3-apps/transformer/Transformer.php';
use Neoan3\Apps\Transformer;

/**
 * Class UserModel
 *
 * @package Neoan3\Model
 * @method static get($id)
 *
 *
 */
class UserModel extends IndexModel
{
    /**
     * @var
     */
    private static $transformer;

    /**
     * @param $method
     * @param $args
     *
     * @return
     */
    static function __callStatic($method,$args){
        if(!self::$transformer){
            self::$transformer = new Transformer(UserTransformer::class,'user');
        }
        return self::$transformer::$method($args);
    }

}
